- alias: "Wakeup - Work"
  trigger:
    platform: time
    after: "06:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.turn_on
    entity_id: script.master_6am_wakeup_weekday


- alias: "Kitchen Study On"
  trigger:
    platform: time
    after: "19:00:00"
  action:
    service: light.turn_on
    entity_id: light.kitchen_study_level_6_0
    data:
      brightness: 25


- alias: "Kitchen Study Off"
  trigger:
    platform: time
    after: "07:00:00"
  action:
    service: light.turn_off
    entity_id: light.kitchen_study_level_6_0
