- alias: "Wakeup - Work"
  trigger:
    platform: template
    value_template: >
      {% set start_time = strptime(states.calendar.working.attributes.start_time, '%Y-%m-%d %H:%M:%S') %}

      {% if start_time.strftime('%Y%m%d') == now().strftime('%Y%m%d') %}
        {% if start_time.strftime('%H')|float|round - 1 == now().strftime('%H')|round %}
          true
        {% endif %}
      {% endif %}
  action:
    service: script.turn_on
    entity_id: script.master_wakeup


- alias: "Kitchen Study On"
  trigger:
    platform: time
    after: "19:00:00"
  action:
    service: script.turn_on_kitchen_study_for_2_hours


- alias: "Turn on laundry room light with motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.__sensor_9_0
      to: 'on'
  action:
    service: script.turn_on_laundry_room_for_5_minutes
