- alias: "Dash Button Dixie Pushed"
  trigger:
    - platform: mqtt
      topic: network/arp/f0:27:2d:89:4e:e5
  condition:
    - condition: state
      entity_id: input_boolean.dixie_theater
      state: 'on'
  action:
    service: script.turn_on
    data_template:
      entity_id: >
        {% if is_state('light.living__bl', 'off') %}
          script.theater_mode_off
        {% else %}
          script.theater_mode_on
        {% endif %}


- alias: "Dash Button Gatorade Pushed"
  trigger:
    - platform: mqtt
      topic: network/arp/f0:27:2d:9e:2d:2a
  condition:
    - condition: state
      entity_id: input_boolean.gatorade_office_light
      state: 'on'
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {% if is_state_attr('light.office__window', 'brightness', 254) %}
          scene.office_tv
        {% else %}
          scene.office_normal
        {% endif %}


- alias: "Dash Button On Pushed"
  trigger:
    - platform: mqtt
      topic: network/arp/44:65:0d:1c:4f:45
  condition:
    - condition: state
      entity_id: input_boolean.on_master_light
      state: 'on'
  action:
    service_template: >
      {% if is_state('light.master_lights_level_2', 'off') %}
        light.turn_on
      {% else %}
        light.turn_off
      {% endif %}
    entity_id: light.master_lights_level_2
