- alias: "Dash Button - Gatorade"
  trigger:
    platform: mqtt
    topic: dash-button/gatorade
  action:
    service: homeassistant.toggle
    entity_id: group.office_lights

- alias: "Dash Button - On"
  trigger:
    platform: mqtt
    topic: dash-button/on
  action:
    service_template: light.toggle
    entity_id: light.lamp_outlet_1_level_11_0
