- alias: "Nest While Home"
  trigger:
    - platform: template
      value_template: "{% if is_state_attr('climate.thermostat', 'away_mode', 'on') %}true{% endif %}"
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    service: climate.set_away_mode
    data:
      away_mode: off


- alias: "Arriving Home"
  trigger:
    - platform: state
      entity_id: group.family
      from: 'not_home'
      to: 'home'
  action:
    service: climate.set_away_mode
    data:
      away_mode: off


- alias: "Nobody Home"
  trigger:
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 30
  action:
    service: script.turn_on
    entity_id: script.nobody_home
