- alias: "Living Room Chromecast playing"
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
  condition:
    - condition: template
      value_template: '{{ states.light.living__bl.state != "off" }}'
  action:
    service: scene.turn_on
    entity_id: scene.living_dim


- alias: "Living Room Chromecast paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.living_room
      from: 'playing'
  condition:
    - condition: template
      value_template: '{{ states.light.living__bl.state != "off" }}'
  action:
    service: scene.turn_on
    entity_id: scene.living_normal


- alias: "Living Room Roku playing"
  trigger:
    - platform: state
      entity_id: media_player.roku_2n0069550469
      to: 'playing'
  condition:
    - condition: template
      value_template: '{{ states.light.living__bl.state != "off" }}'
  action:
    service: scene.turn_on
    entity_id: scene.living_dim


- alias: "Living Room Roku paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.roku_2n0069550469
      from: 'playing'
  condition:
    - condition: template
      value_template: '{{ states.light.living__bl.state != "off" }}'
  action:
    service: scene.turn_on
    entity_id: scene.living_normal
