- alias: "Living Room Media"
  initial_state: False
  trigger:
    - platform: state
      entity_id: media_player.living_room, media_player.roku_2n0069550469, media_player.lgroku_tv__2n0069550469
  condition:
    - condition: template
      value_template: '{{ states.light.living__bl.state != "off" }}'
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {% if trigger.to_state.state == 'playing' %}
          scene.living_dim
        {% else %}
          scene.living_normal
        {% endif %}


- alias: "Office Media"
  initial_state: False
  trigger:
    - platform: state
      entity_id: media_player.office, media_player.roku_1gn387145507, media_player.roku_3__1gn387145507
  condition:
    - condition: template
      value_template: '{{ states.light.office__desks.state != "off" }}'
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {% if trigger.to_state.state == 'playing' %}
          scene.office_tv
        {% else %}
          scene.office_normal
        {% endif %}
