- alias: "Office Chromecast playing"
  trigger:
    - platform: state
      entity_id: media_player.office
      state: 'playing'
  condition:
    - condition: template
      value_template: '{{ states.light.office__desks.state != "off" }}'
  action:
    service: scene.turn_on
    entity_id: scene.office_tv


- alias: "Office Chromecast paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.office
      from: 'playing'
  condition:
    - condition: template
      value_template: '{{ states.light.office__desks.state != "off" }}'
  action:
    service: scene.turn_on
    entity_id: scene.office_normal


- alias: "Office Roku playing"
  trigger:
    - platform: state
      entity_id: media_player.roku_1gn387145507
      state: 'playing'
  condition:
    - condition: template
      value_template: '{{ states.light.office__desks.state != "off" }}'
  action:
    service: scene.turn_on
    entity_id: scene.office_tv


- alias: "Office Roku no video"
  trigger:
    - platform: state
      entity_id: media_player.roku_1gn387145507
      from: 'playing'
  condition:
    - condition: template
      value_template: '{{ states.light.office__desks.state != "off" }}'
  action:
    service: scene.turn_on
    entity_id: scene.office_normal
