- alias: "Office Chromecast playing"
  trigger:
    - platform: state
      entity_id: media_player.brent_office
      state: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.media_office
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.office_tv


- alias: "Office Chromecast paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.brent_office
      from: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.media_office
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.office_normal


- alias: "Office Roku playing"
  trigger:
    - platform: state
      entity_id: media_player.roku_1gn387145507
      state: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.media_office
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.office_tv


- alias: "Office Roku no video"
  trigger:
    - platform: state
      entity_id: media_player.roku_1gn387145507
      from: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.media_office
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.office_normal
