homeassistant:
  name: Hughes House
  latitude: !env_var HOME_LATITUDE
  longitude: !env_var HOME_LONGITUDE
  unit_system: imperial
  time_zone: America/Chicago
  elevation: 178

  customize: !include customize.yaml

http:
  api_password: !env_var HA_PASSWORD
  server_port: 8123

recorder:
  db_url: !env_var MYSQL_CONNECTION_STRING





##############
# COMPONENTS #
##############
light:
  platform: hue
  host: 192.168.1.9
  allow_unreachable: true

climate:
  platform: nest

nest:
  username: !env_var NEST_EMAIL
  password: !env_var NEST_PASSWORD

mqtt:
  broker: 192.168.1.10
  port: 8883
  username: !env_var MQTT_USERNAME
  password: !env_var MQTT_PASSWORD
  certificate: /certs/ca.crt

zwave:
  usb_path: /dev/zwave
  config_path: /usr/local/share/python-openzwave/config
  polling_interval: 40000

statsd:
  host: 192.168.1.10
  port: 8125
  prefix: !env_var STATSD_PREFIX
  rate: 1
  log_attributes: true

emulated_hue:
  host_ip: 192.168.1.10
  expose_by_default: true
  exposed_domains:
    - light
    - switch

google:
  client_id: !env_var GOOGLE_OAUTH_CLIENT_ID
  client_secret: !env_var GOOGLE_OAUTH_CLIENT_SECRET
  track_new_calendar: false


#########
# ZONES #
#########
zone 1:
  name: Home
  latitude: !env_var HOME_LATITUDE
  longitude: !env_var HOME_LONGITUDE
  radius: 500
  icon: mdi:home

zone 2:
  name: Brent Work
  latitude: !env_var BRENT_WORK_LATITUDE
  longitude: !env_var BRENT_WORK_LONGITUDE
  radius: 500
  icon: mdi:briefcase





############
# INCLUDES #
############
group: !include_dir_merge_named includes/groups
sensor: !include_dir_merge_list includes/sensors
device_tracker: !include includes/device_trackers.yaml
media_player: !include includes/media_players.yaml
scene: !include includes/scenes.yaml
notify: !include includes/notify.yaml
script: !include_dir_named includes/scripts
automation: !include_dir_merge_list includes/automation
camera: !include includes/cameras.yaml

alexa:
  intents: !include_dir_merge_named includes/alexa





##########
# EXTRAS #
##########
logger:
  default: error
  logs:
    homeassistant: !env_var HA_LOG_LEVEL
    homeassistant.core: error
    homeassistant.bootstrap: error
    homeassistant.components.http: error
    homeassistant.components.api: error
    homeassistant.components.recorder: error
    homeassistant.components.device_tracker: error
    homeassistant.components.statsd: error
    homeassistant.components.mqtt: error
    homeassistant.components.sensor.command_line: error
    homeassistant.components.zwave: error
    homeassistant.components.sensor.google_travel_time: error


logbook:
  exclude:
    entities:
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_humidity
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
    domains:
      - group



frontend:
history:
