settings:
  name: Settings
  view: yes
  icon: mdi:settings
  entities:
    - group.global_settings
    - group.notification_settings
    - group.kitchen_settings
    - group.living_room_settings
    - group.office_settings
    - group.master_bedroom_settings
    - group.laundry_room_settings




global_settings:
  name: Global
  entities:
    - automation.arriving_home
    - automation.nobody_home
    - automation.nest_while_home

notification_settings:
  name: Notifications
  entities:
    - automation.brent_leave_work
    - automation.emma_leave_home
    - automation.front_door_motion
    - automation.driveway_motion

master_bedroom_settings:
  name: Master Bedroom
  entities:
    - automation.wakeup__work

kitchen_settings:
  name: Kitchen
  entities:
    - automation.kitchen_study_off
    - automation.kitchen_study_on

living_room_settings:
  name: Living Room
  entities:
    - automation.living_room_chromecast_pausedstopped
    - automation.living_room_chromecast_playing
    - automation.living_room_roku_pausedstopped
    - automation.living_room_roku_playing

office_settings:
  name: Office
  entities:
    - automation.office_chromecast_pausedstopped
    - automation.office_chromecast_playing
    - automation.office_roku_no_video
    - automation.office_roku_playing

laundry_room_settings:
  name: Laundry Room
  entities:
    - automation.turn_on_laundry_room_light_for_10_minutes
    - automation.turn_on_laundry_room_light_when_brent_arrives_home
    - automation.turn_on_laundry_room_light_when_emma_arrives_home