- platform: darksky
  api_key: !env_var DARK_SKY_API
  monitored_conditions:
    - summary
    - precip_type
    - precip_probability
    - temperature
    - humidity
    - temperature_max
    - temperature_min

- platform: nest
  monitored_conditions:
    - 'temperature'
    - 'target'
    - 'humidity'
    - 'operation_mode'


- platform: mqtt
  name: Camera - Front Door
  state_topic: "security/cameras/front_door"

- platform: mqtt
  name: Camera - Driveway
  state_topic: "security/cameras/driveway"