- platform: forecast
  api_key: !env_var DARK_SKY_API
  monitored_conditions:
    - summary
    - precip_type
    - precip_probability
    - temperature
    - humidity
    - temperature_max
    - temperature_min
