- platform: mjpeg
  mjpeg_url: http://192.168.1.11/cgi-bin/nph-zms?mode=jpeg&monitor=3&maxfps=15
  name: Front Door

# - platform: generic
#   still_image_url: http://192.168.1.41/cgi-bin/snapshot.cgi
#   name: Driveway
