- platform: plex

# Living room
- platform: cast
  host: 192.168.1.109

- platform: roku
  host: 192.168.1.146

# Office
- platform: cast
  host: 192.168.1.134

- platform: roku
  host: 192.168.1.138
